[platformio]
default_envs = xteink_x4

[env:xteink_x4]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D EINK_DISPLAY_SINGLE_BUFFER_MODE
lib_deps =
    symlink://open-x4-sdk/libs/display/EInkDisplay
    bblanchon/ArduinoJson@^6.21.5
    https://github.com/lvandeve/lodepng.git
